version: '2'
services:
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=spring_demo
      - MYSQL_USER=jordan
      - MYSQL_PASSWORD=1234
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci